routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home'); 
Route::post("/register/regDato", array('uses' => 'App\Http\Controllers\RegisterController@registraDatos'));
// [imprime solicitud]
Route::get('/register/imprimeSolicitud_afp/{id}', ['uses' => 'App\Http\Controllers\RegisterController@reporteDocumento']);
// Route::post("/register/{id}/regDato", array('uses' => 'App\Http\Controllers\RegisterController@registraDatos'));

// $ruta = request()->segments();
// $urlAccion = $ruta == null? '' : $ruta[0];
// $action = $ruta == null? '' : (isset($ruta[1])? $ruta[1] : '');

// Route::group(['middleware' => 'auth'], function () {
    $controller = 'App\Http\Controllers';
    $ruta = request()->segments();
    $urlAccion = $ruta == null? '' : $ruta[0]; 

    $action = $ruta == null? '' : (isset($ruta[1])? $ruta[1] : '');

    // ---------------------------------------------------------------------------------
    // -------------------------- Pestaña [ ADMINISTRACIÓN ] ---------------------------
    // ---------------------------------------------------------------------------------
    // [personal]
    route::resource('personal', $controller.'\Administracion\DatosgenericosController');
    // [roles]
    route::resource('roles', $controller.'\Administracion\RolesController');
    // ---------------------------------------------------------------------------------

    route::resource('almacen', $controller.'\AlmacenController');
	// ---------------------------------------------------------------------------------
    // ----------------------------- Pestaña [ AFILIACIÓN ] ----------------------------
    // ---------------------------------------------------------------------------------
    // [poblacion]
    route::resource('hcl_poblacion', $controller.'\Afiliacion\Hcl_poblacionController'); 
    Route::post($urlAccion."/buscaEmpleadorCreate", array('uses' => $controller.'\Afiliacion\Hcl_poblacionController@buscaEmpleador'));
    Route::post($urlAccion."/{id}/buscaEmpleador", array('uses' => $controller.'\Afiliacion\Hcl_poblacionController@buscaEmpleador'));
    Route::post("/hcl_poblacion/buscaParentescoCreate", array('uses' => $controller.'\Afiliacion\Hcl_poblacionController@buscaParentesco'));
    Route::get("/hcl_poblacion/{id}/createBeneficiario", array('as' => 'createBeneficiario', 'uses' => $controller.'\Afiliacion\Hcl_poblacionController@createBeneficiario'));
    Route::post("/hcl_poblacion/{id}/beneficiario", array('as' => 'storeBeneficiario', 'uses' => $controller.'\Afiliacion\Hcl_poblacionController@storeBeneficiario'));
    Route::resource('seg_ficha_generada', $controller.'\Seguimiento\Seg_ficha_generadaController');
    
    // [empresa]
    route::resource('empresa', $controller.'\Afiliacion\Hcl_empleadorController');
    // [cuaderno]
    route::resource('cuaderno', $controller.'\Afiliacion\Hcl_cuadernoController');
    // [cuaderno_personal]
    route::resource('cuaderno_personal', $controller.'\Afiliacion\Hcl_cuaderno_personalController');
    // Route::post("/cuaderno_personal/{id}/buscaMedico", array('uses' => 'App\Http\Controllers\Administracion\DatosgenericosController@busca_Medico'));
    // [plantilla_personal]
    route::resource('plantilla_personal', $controller.'\Afiliacion\Hcl_plantillaController'); 
     // [reporte]  
    route::resource('hcl_reporte', $controller.'\Salud\PdfController');
    Route::get('hcl_reporte/imprimeDocumento/{id}', array('uses' => $controller.'\Salud\PdfController@imprimeDocumento'));


    // ---------------------------------------------------------------------------------------------
    // -------------------------------------- [ MEDICINA DEL TRABAJO ] --------------------------------------
    // ---------------------------------------------------------------------------------------------
    // [med_clasificacion]
    Route::resource('med_clasificacion', $controller.'\Medicina_trabajo\Med_clasificacionController'); 
    // [med_administracion]
    Route::resource('med_administracion', $controller.'\Medicina_trabajo\Med_administracionController'); 
    // [med_registro]
    Route::resource('med_registro', $controller.'\Medicina_trabajo\Med_registroController'); 
    // // [med_datos]
    // Route::resource('med_datos', 'Medicina_trabajo\Med_datosController'); 
    // [med_lista_cargos]
    Route::resource('med_lista_cargos', $controller.'\Medicina_trabajo\Med_lista_cargosController'); 
    Route::post("/".$urlAccion."/buscarPersona", array('uses' => $controller.'\Medicina_trabajo\Med_lista_cargosController@buscar_Persona')); 
    Route::post("/".$urlAccion."/asignaCargo", array('uses' => $controller.'\Medicina_trabajo\Med_lista_cargosController@asigna_Cargo')); 
    Route::post($urlAccion."/buscaClasificacionCreate", array('uses' => $controller.'\Medicina_trabajo\Med_clasificacionController@buscaMed_clasificacion'));

    // Route::post($urlAccion."/buscaClasificacionCreate", array('uses' => 'Medicina_trabajo\Med_clasificacionController@buscaMed_clasificacion'));
    // [imprime solicitud]
    Route::get($urlAccion.'/imprimeSolicitud_Salud/{id}', ['uses' => $controller.'\Medicina_trabajo\ReporteController@reporteDocumento']);
    // [valida datos] 
    Route::post($urlAccion."/{id}/validarRegistro", array('uses' => $controller.'\Medicina_trabajo\Med_registroController@validarRegistro'));
    // [Elimina datos] 
    Route::post($urlAccion."/{id}/eliminarRegistro", array('uses' => $controller.'\Medicina_trabajo\Med_registroController@eliminarRegistro'));
    // [med_cuaderno_personal]
    Route::resource('med_cuaderno_personal', $controller.'\Medicina_trabajo\Med_cuaderno_personalController'); 

    // [hsi_actividad_economica_division]
    Route::resource('hsi_division', $controller.'\Medicina_trabajo\Hsi_actividad_economica_divisionController'); 
    // [hsi_actividad_economica_agrupacion]
    Route::resource('hsi_agrupacion', $controller.'\Medicina_trabajo\Hsi_actividad_economica_agrupacionController'); 
    // [hsi_tipo_registro]
    Route::resource('hsi_tipo_registro', $controller.'\Medicina_trabajo\Hsi_tipo_registroController'); 
    // [hsi_tipo]
    Route::resource('hsi_tipo', $controller.'\Medicina_trabajo\Hsi_tipoController'); 
    // [hsi_registro_datos]
    Route::resource('hsi_registro_datos', $controller.'\Medicina_trabajo\Hsi_registro_datosController'); 
    Route::post($urlAccion."/buscaPaciente_hsiCreate", array('uses' => $controller.'\Medicina_trabajo\Hsi_registro_datosController@buscaPaciente_hsi'));
    Route::post($urlAccion."/{id}/buscaPaciente_hsi", array('uses' => $controller.'\Medicina_trabajo\Hsi_registro_datosController@buscaPaciente_hsi'));

    Route::post($urlAccion."/buscaHsi_divisionCreate", array('uses' => $controller.'\Medicina_trabajo\Hsi_actividad_economica_divisionController@buscaHsi_division'));
    Route::post($urlAccion."/{id}/buscaHsi_division", array('uses' => $controller.'\Medicina_trabajo\Hsi_actividad_economica_divisionController@buscaHsi_division'));
    Route::post($urlAccion."/muestraDatosHsiCreate", array('uses' => $controller.'\Medicina_trabajo\Hsi_tipoController@muestraDatosHsi'));
    Route::post($urlAccion."/{id}/muestraDatosHsi", array('uses' => $controller.'\Medicina_trabajo\Hsi_tipoController@muestraDatosHsi'));  

    Route::post($urlAccion."/buscaPaciente_solicitudCreate", array('uses' => $controller.'\Medicina_trabajo\Med_registroController@buscaPaciente_solicitud'));
    Route::post($urlAccion."/{id}/buscaPaciente_solicitud", array('uses' => $controller.'\Medicina_trabajo\Med_registroController@buscaPaciente_solicitud'));
      
    // [med_programacion]
    // Route::resource('med_programacion', 'Medicina_trabajo\Med_programacionController'); 
    // // -------------------->> "Programados"
    // Route::post($urlAccion."/buscaPoblacion_med", ['uses' => 'Medicina_trabajo\Med_programacionController@buscaPoblacionMed']);
    // Route::post($urlAccion."/{id}/buscaPoblacion_med", ['uses' => 'Medicina_trabajo\Med_programacionController@buscaPoblacionMed']);
    // ------------------------------------ [ FIN MEDICINA DEL TRABAJO ] ------------------------------------

    // ---------------------------------------------------------------------------------
    // ------------------------------ Pestaña [ FARMACIA ] -----------------------------
    // ---------------------------------------------------------------------------------
    // [TIPOS DE TRANSACCIONES]
    route::resource('far_adm_tipotransaccion', $controller.'\Farmacia\Far_adm_tipotransaccionController');
    // [far_sucursales]
    route::resource('sucursal', $controller.'\Farmacia\Far_sucursalesController'); 
    // [far_adm_articulo]
    route::resource('articulo', $controller.'\Farmacia\Far_adm_articuloController'); 
    // ------------------------------------ [ FIN FARMACIA ] ------------------------------------
    
    // ---------------------------------------------------------------------------------
    // ------------------------------- Pestaña [ SALUD ] -------------------------------
    // ---------------------------------------------------------------------------------
    // [consulta_externa]
    
    route::resource('hcl_cabecera_registro', $controller.'\Salud\Hcl_cabecera_registroController');
    route::resource('hcl_lista_atencion', $controller.'\Salud\Hcl_lista_atencionController');

app/Models/Administracion/Adm_estados.php
<?php
namespace App\Models\Administracion;

use Illuminate\Database\Eloquent\Model;

class Adm_estados extends Model
{
	// protected $table = 'ima_estado';
	// public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
		
	const VIGENTE = 0;
	const NO_VIGENTE = 1;
	
}

app/Models/Administracion/Datosgenericos.php
<?php
namespace App\Models\Administracion;

use Illuminate\Database\Eloquent\Model;

class Datosgenericos extends Model
{
	protected $table = 'datosgenericos';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Http/Controllers/Administracion/RolesController.php
<?php
namespace App\Http\Controllers\Administracion;
use App\Http\Controllers\Controller;

use App\Http\Requests;
use App\Http\Requests\AlmacenRequest;
use \App\Models\Almacen\Almacen; 
use Illuminate\Http\Request; 
use Auth;
use \App\Models\Almacen\Home;
use \App\Permission;
use \App\Models\Usuario\Almacenusuario;

use \App\Models\Administracion\Roles;
use \App\Models\Administracion\Menu;
use \App\Models\Administracion\Menuopcion;

use Session;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\DB;

class RolesController extends Controller
{
    private $rutaVista = 'Administracion.roles.';
    private $controlador = 'roles';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    } 

    public function index(Request $request)
    {
        $arrayDatos = Home::parametrosSistema();
        $arrayDatos['mini'] = 1; 
        $model = Roles::get();   
        
        $view = $this->rutaVista . 'index';        
        $model->accion = $this->controlador;
        $model->scenario = 'index';
        $model->rutaview = $this->rutaVista;

        return view($view)
                ->with('model', $model)  
                ->with('arrayDatos', $arrayDatos);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $arrayDatos = Home::parametrosSistema();

        
        $model = new Roles;    
        $modelMenu = Menu::all();   
        $modelOpcion = Menuopcion::all();   


        $model->accion = $this->controlador;
        $model->scenario = 'create';
        $model->rutaview = $this->rutaVista; 

        if(!Session::has('url_'.$this->controlador))
            Session::put('url_'.$this->controlador, URL::previous());
        return view($model->rutaview.'create')
                ->with('model', $model) 
                ->with('modelMenu', $modelMenu) 
                ->with('modelOpcion', $modelOpcion) 
                ->with('arrayDatos', $arrayDatos);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    protected function store(Request $request)
    {
        $model = new Hsi_tipo;
        $model->idhsi_tipo_registro = $request->idhsi_tipo_registro;        
        $model->codigo = $request->codigo;        
        $model->nombre = $request->nombre;           
        $model->usuario = Auth::user()->name;

        if($model->save()){ 
            $mensaje = config('app.mensajeGuardado');
        }
        else
            $mensaje = config('app.mensajeErrorGuardado');

        if(Session::has('url_'.$this->controlador))
        {
            $sesion = Session::get('url_'.$this->controlador);
            Session::forget('url_'.$this->controlador);
            return redirect()->to($sesion)
                            ->with('message', 'store')
                            ->with('mensaje', $mensaje);
        }
        else
            return redirect($this->controlador); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }
 
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $arrayDatos = Home::parametrosSistema();

        $model = Hsi_tipo::find($id);
        $modelRegistro = Hsi_tipo_registro::get();  

        $model->accion = $this->controlador;
        $model->scenario = 'edit';
        $model->rutaview = $this->rutaVista;
        
        if(!Session::has('url_'.$this->controlador))
            Session::put('url_'.$this->controlador, URL::previous());
        return view($model->rutaview.'edit')
                ->with('model', $model)
                ->with('modelRegistro', $modelRegistro)
                ->with('arrayDatos', $arrayDatos);
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {         
        $model = Hsi_tipo::find($id); 
        $model->idhsi_tipo_registro = $request->idhsi_tipo_registro;        
        $model->codigo = $request->codigo;        
        $model->nombre = $request->nombre;            
        $model->usuario = Auth::user()->name;

        if($model->save())
            $mensaje = config('app.mensajeGuardado');
        else
            $mensaje = config('app.mensajeErrorGuardado');
        
        if(Session::has('url_'.$this->controlador))
        {
            $sesion = Session::get('url_'.$this->controlador);
            Session::forget('url_'.$this->controlador);
            return redirect()->to($sesion)
                            ->with('message', 'update')
                            ->with('mensaje', $mensaje);
        }
        else
            return redirect($this->controlador);
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    }

    // ---------------------------------------------------------------------------------------------------------
    // ---------------------------------------------- [BUSCADORES] ---------------------------------------------
    // ---------------------------------------------------------------------------------------------------------
    public function buscaPaciente_hsi()
    {
        if(isset($_POST['dato']))
        {
            $dato = $_POST['dato'];

            // $modelo = Hcl_poblacion::where(function($query) use($dato) {
            //             $query->orwhere('numero_historia', 'ilike', '%'.$dato.'%');
            //             $query->orwhere('nombre', 'ilike', '%'.$dato.'%');
            //             $query->orwhere('primer_apellido', 'ilike', '%'.$dato.'%');
            //             $query->orwhere('segundo_apellido', 'ilike', '%'.$dato.'%');
            //             $query->orwhere(DB::raw("CONCAT(nombre, ' ',primer_apellido, ' ', segundo_apellido)"), 'ilike', '%'.$dato.'%');
            //         })
            //         ->select('hcl_poblacion.*', 
            //                 DB::raw("(SELECT date_part('year', age(fecha_nacimiento)))::integer AS edad"))
            //         ->take(config('app.muestraTotalBusqueda'))
            //         ->get();
            
            $modelo = DB::table(DB::raw("hsi_busca_paciente('".$dato."','".$dato."','".$dato."','".$dato."')"))->take(config('app.muestraTotalBusqueda'))->get();   

            echo json_encode($modelo);
        }
    }
    // ------------------------------------------------------------------------------------------------------
    // ------------------------------------------------------------------------------------------------------

}

resources/views/Administracion/datosgenericos/create.blade.php
@extends('adminlte::page') 
@section('title', 'NUEVO REGISTRO')  
@section('content_header')
    <h1>NUEVO REGISTRO DE PERSONAL</h1>
@stop
 
@section('content')
<div class="row">
	<div class="col-xs-12 col-sm-10 col-md-12 col-lg-12">
		<div class="card">
			<div class="card-body">   
				<form method="POST" action="{{ route('personal.store') }}" autocomplete="off" id="form">
					{{ csrf_field() }}
					@include($model->rutaview.'form') 
				</form>
			</div>
		</div>
	</div>
</div>
@stop

resources/views/Administracion/datosgenericos/edit.blade.php
@extends('adminlte::page') 
@section('title', 'EDITAR REGISTRO')  
@section('content_header')
    <h1>EDITAR REGISTRO DE USUARIO</h1>
@stop
 
@section('content')
<div class="row">
	<div class="col-xs-12 col-sm-10 col-md-12 col-lg-12">
		<div class="card">
			<div class="card-body">  
				<form method="POST" action="{{ route('personal.update', $model->id) }}" autocomplete="off" id="form">
					{{ csrf_field() }}
      				<input name="_method" type="hidden" value="PATCH"> 
					@include($model->rutaview.'form') 
				</form>
			</div>
		</div>
	</div>
</div>
@stop

resources/views/Administracion/datosgenericos/form.blade.php
<div class="form-group">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <input type="hidden" id="txtAccion" value="{{ $model->accion }}">
    <input type="hidden" id="txtScenario" value="{{ $model->scenario }}">

    <div class="row">
      @if(count($errors) > 0)
        <div class="col-xs-9">
          <div class="panel panel-danger">
            <div class="panel-heading">VALIDACIONES</div>
              <div class="panel-body">
                <ul class="list-group">
              @foreach($errors->all() as $error)
                <h4 style="color: #ad0d0c;">
                  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                  {{ $error }}
                </h4>
              @endforeach
              </ul>
            </div>
          </div>
        </div>
      @endif
    </div>
    
    <div class="row">
      <div class="col-xs-12 col-sm-11 col-md-6 col-lg-6">
        <label class="bmd-label">Nombres:</label> <br>  
        <input type="text" class="form-control" id="nombres" name="nombres" style="text-transform:uppercase;" value="{{$model->nombres}}"> 
      </div>
      <div class="col-xs-12 col-sm-11 col-md-6 col-lg-6">
        <label class="bmd-label">Apellidos:</label> <br>  
        <input type="text" class="form-control" id="apellidos" name="apellidos" style="text-transform:uppercase;" value="{{$model->apellidos}}">  
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-11 col-md-6 col-lg-6">
        <label class="bmd-label">Dirección:</label> <br>  
        <input type="text" class="form-control" id="direccion" name="direccion" style="text-transform:uppercase;" value="{{$model->direccion}}"> 
      </div>
      <div class="col-xs-12 col-sm-11 col-md-6 col-lg-6">
        <label class="bmd-label">Carnet de Identidad:</label> <br>  
        <input type="text" class="form-control" id="ci" name="ci" style="text-transform:uppercase;" value="{{$model->ci}}">  
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-11 col-md-6 col-lg-6">
        <label class="bmd-label">Matricula:</label> <br>  
        <input type="text" class="form-control" id="matricula" name="matricula" style="text-transform:uppercase;" value="{{$model->matricula}}"> 
      </div>
      <div class="col-xs-12 col-sm-11 col-md-6 col-lg-6">
        <label class="bmd-label">Título:</label> <br>  
        <input type="text" class="form-control" id="titulo" name="titulo" style="text-transform:uppercase;" value="{{$model->titulo}}">  
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-11 col-md-6 col-lg-6">
        <label class="bmd-label">Telefono:</label> <br>  
        <input type="text" class="form-control" id="telefono" name="telefono" style="text-transform:uppercase;" value="{{$model->telefono}}">   
      </div>
      <div class="col-xs-12 col-sm-11 col-md-6 col-lg-6">
        <label class="bmd-label">Descripción:</label> <br>  
        <input type="text" class="form-control" id="descripcion" name="descripcion" style="text-transform:uppercase;" value="{{$model->descripcion}}"> 
      </div>
    </div>    
    <div class="row">
      <div class="col-xs-12 col-sm-11 col-md-6 col-lg-6"> 
        <label>TIPO DE PERSONAL</label>
        <br>
        <select name="id_generico" id="id_generico" class="form-control" onchange="seleccionarClasificacion()"> 
            <option disabled selected>Seleccionar</option> 
            @foreach($modelGenerico as $dato) 
              @if($model != null)
                <option value="{{$dato->id}}" {{ $model->id_generico == $dato->id ? 'selected="selected"' : ''  }} >{{$dato->nombre }}</option> 
              @else
                <option value="{{$dato->id}}">{{$dato->nombre}}</option> 
              @endif
            @endforeach
        </select>   
      </div>
      <div class="col-xs-12 col-sm-11 col-md-6 col-lg-6">
        <label>UNIDAD MEDICA</label>
        <br>
        <select name="idalmacen" id="idalmacen" class="form-control" onchange="seleccionarClasificacion()"> 
            <option disabled selected>Seleccionar</option> 
            @foreach($modelAlmacen as $dato) 
              @if($model != null)
                <option value="{{$dato->id}}" {{ $model->idalmacen == $dato->id ? 'selected="selected"' : ''  }} >{{$dato->nombre }}</option> 
              @else
                <option value="{{$dato->id}}">{{$dato->nombre}}</option> 
              @endif
            @endforeach
        </select>  
      </div>
    </div>    
</div>

<a href="{{ URL::previous() }}" class="btn btn-primary">
  <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver
</a>
@if($model->scenario != 'view')
  <button type="submit" class="btn btn-success">
    <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> Guardar
  </button>
@endif

resources/views/Administracion/datosgenericos/index.blade.php
@extends('adminlte::page')
@section('title', 'LISTA DE REGISTROS')
@section('content_header')
    <h1>LISTA DE REGISTROS - USUARIOS</h1>
@stop   

@section('content')
<div class="card"> 
	<input type="hidden" id="txtScenario" value="{{ $model->scenario }}"> 
	<div class="card-header">
	 	<div class="row"> 
			<div class="col-xs-3 col-sm-3 col-md-2 col-lg-2" style="text-align: left;">
				<!-- <div class="row" style="height: 6px; color: transparent;">.</div> -->
		        <a type="button" class="btn btn-primary" href="{{ route('personal.create') }}">
		            <span class="fa fa-plus" aria-hidden="true"></span> Nuevo
		        </a>
		    </div> 
		</div>
	</div>
 
	<div class="card-body"> 
		<table id="empleador" class="table table-striped">
			<thead>
				<tr>
					<th>Nombres/Apellidos</th> 
 					<th>CI</th>
 					<th>Titulo</th>
 					<th>Matricula</th>
 					<th>Dirección</th>
 					<th>Telefono</th> 					
 					<th></th> 
				</tr> 
			</thead>
			<tbody id="indexContent">
				@include($model->rutaview.'indexContent')
			</tbody>
		</table>
	</div>  
</div> 
@stop

@section('js')
	<script>
		$(document).ready( function () {
		    $('#empleador').DataTable({
		    	"language":{
		    		"search": "Buscar",
		    		"lengthMenu": "Mostrar _MENU_ registros por página",
		    		"info": "Mostrando página _PAGE_ de _PAGES_",
		    		"paginate":{
			    		"previous": "Anterior",
			    		"next": "Siguiente",
			    		"first": "Primero",
			    		"last": "Ultimo"
			    	}
		    	}
		    });
		} );
	</script>	
@endsection 

resources/views/Administracion/datosgenericos/indexContent.blade.php
@foreach($model as $dato)
    <tr role="row" style="{{ config('app.styleTableRow') }}">
		<td class="col-xs-4">{{ $dato->nombres.' '.$dato->apellidos }}</td> 
		<td class="col-xs-1">{{ $dato->ci }}</td>
		<td class="col-xs-1">{{ $dato->titulo }}</td>
		<td class="col-xs-1">{{ $dato->matricula }}</td>
		<td class="col-xs-2">{{ $dato->direccion }}</td>
		<td class="col-xs-1">{{ $dato->telefono }}</td>  
		<td class="col-xs-1">
			<!-- <a href="{{ route('personal.show', $dato->id) }}" type="button" class="btn btn-default btn-sm" title="VER">
				<span class="glyphicon glyphicon-eye-open"></span>
			</a> -->
			<a href="{{ route('personal.edit', $dato->id) }}" class="btn btn-default btn-sm" title="Editar">
				<i class="fa fa-edit"></i>
			</a>
		</td>
	</tr>
@endforeach

resources/views/Administracion/datosgenericos/view.blade.php
@extends('adminlte::layouts.app')
@section('contentheader_title', 'VER DATOS')
@section('htmlheader_title', 'VER DATOS')
 
@section('main-content')
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="panel panel-primary">
      <div class="panel-body">
        {!! Form::model($model, ['route' => ['personal.show', $model->id], 'method' => 'PUT', 'id' => 'form']) !!}
          @include($model->rutaview.'form')
        {!! Form::close() !!}
      </div>
    </div>
  </div>
</div>
@stop