routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home'); 
Route::post("/register/regDato", array('uses' => 'App\Http\Controllers\RegisterController@registraDatos'));
// [imprime solicitud]
Route::get('/register/imprimeSolicitud_afp/{id}', ['uses' => 'App\Http\Controllers\RegisterController@reporteDocumento']);
// Route::post("/register/{id}/regDato", array('uses' => 'App\Http\Controllers\RegisterController@registraDatos'));

// $ruta = request()->segments();
// $urlAccion = $ruta == null? '' : $ruta[0];
// $action = $ruta == null? '' : (isset($ruta[1])? $ruta[1] : '');

// Route::group(['middleware' => 'auth'], function () {
    $controller = 'App\Http\Controllers';
    $ruta = request()->segments();
    $urlAccion = $ruta == null? '' : $ruta[0]; 

    $action = $ruta == null? '' : (isset($ruta[1])? $ruta[1] : '');

    // ---------------------------------------------------------------------------------
    // -------------------------- Pestaña [ ADMINISTRACIÓN ] ---------------------------
    // ---------------------------------------------------------------------------------
    // [personal]
    route::resource('personal', $controller.'\Administracion\DatosgenericosController');
    // [roles]
    route::resource('roles', $controller.'\Administracion\RolesController');
    // ---------------------------------------------------------------------------------

    route::resource('almacen', $controller.'\AlmacenController');
	// ---------------------------------------------------------------------------------
    // ----------------------------- Pestaña [ AFILIACIÓN ] ----------------------------
    // ---------------------------------------------------------------------------------
    // [poblacion]
    route::resource('hcl_poblacion', $controller.'\Afiliacion\Hcl_poblacionController'); 
    Route::post($urlAccion."/buscaEmpleadorCreate", array('uses' => $controller.'\Afiliacion\Hcl_poblacionController@buscaEmpleador'));
    Route::post($urlAccion."/{id}/buscaEmpleador", array('uses' => $controller.'\Afiliacion\Hcl_poblacionController@buscaEmpleador'));
    Route::post("/hcl_poblacion/buscaParentescoCreate", array('uses' => $controller.'\Afiliacion\Hcl_poblacionController@buscaParentesco'));
    Route::get("/hcl_poblacion/{id}/createBeneficiario", array('as' => 'createBeneficiario', 'uses' => $controller.'\Afiliacion\Hcl_poblacionController@createBeneficiario'));
    Route::post("/hcl_poblacion/{id}/beneficiario", array('as' => 'storeBeneficiario', 'uses' => $controller.'\Afiliacion\Hcl_poblacionController@storeBeneficiario'));
    Route::resource('seg_ficha_generada', $controller.'\Seguimiento\Seg_ficha_generadaController');
    
    // [empresa]
    route::resource('empresa', $controller.'\Afiliacion\Hcl_empleadorController');
    // [cuaderno]
    route::resource('cuaderno', $controller.'\Afiliacion\Hcl_cuadernoController');
    // [cuaderno_personal]
    route::resource('cuaderno_personal', $controller.'\Afiliacion\Hcl_cuaderno_personalController');
    // Route::post("/cuaderno_personal/{id}/buscaMedico", array('uses' => 'App\Http\Controllers\Administracion\DatosgenericosController@busca_Medico'));
    // [plantilla_personal]
    route::resource('plantilla_personal', $controller.'\Afiliacion\Hcl_plantillaController'); 
     // [reporte]  
    route::resource('hcl_reporte', $controller.'\Salud\PdfController');
    Route::get('hcl_reporte/imprimeDocumento/{id}', array('uses' => $controller.'\Salud\PdfController@imprimeDocumento'));


    // ---------------------------------------------------------------------------------------------
    // -------------------------------------- [ MEDICINA DEL TRABAJO ] --------------------------------------
    // ---------------------------------------------------------------------------------------------
    // [med_clasificacion]
    Route::resource('med_clasificacion', $controller.'\Medicina_trabajo\Med_clasificacionController'); 
    // [med_administracion]
    Route::resource('med_administracion', $controller.'\Medicina_trabajo\Med_administracionController'); 
    // [med_registro]
    Route::resource('med_registro', $controller.'\Medicina_trabajo\Med_registroController'); 
    // // [med_datos]
    // Route::resource('med_datos', 'Medicina_trabajo\Med_datosController'); 
    // [med_lista_cargos]
    Route::resource('med_lista_cargos', $controller.'\Medicina_trabajo\Med_lista_cargosController'); 
    Route::post("/".$urlAccion."/buscarPersona", array('uses' => $controller.'\Medicina_trabajo\Med_lista_cargosController@buscar_Persona')); 
    Route::post("/".$urlAccion."/asignaCargo", array('uses' => $controller.'\Medicina_trabajo\Med_lista_cargosController@asigna_Cargo')); 
    Route::post($urlAccion."/buscaClasificacionCreate", array('uses' => $controller.'\Medicina_trabajo\Med_clasificacionController@buscaMed_clasificacion'));

    // Route::post($urlAccion."/buscaClasificacionCreate", array('uses' => 'Medicina_trabajo\Med_clasificacionController@buscaMed_clasificacion'));
    // [imprime solicitud]
    Route::get($urlAccion.'/imprimeSolicitud_Salud/{id}', ['uses' => $controller.'\Medicina_trabajo\ReporteController@reporteDocumento']);
    // [valida datos] 
    Route::post($urlAccion."/{id}/validarRegistro", array('uses' => $controller.'\Medicina_trabajo\Med_registroController@validarRegistro'));
    // [Elimina datos] 
    Route::post($urlAccion."/{id}/eliminarRegistro", array('uses' => $controller.'\Medicina_trabajo\Med_registroController@eliminarRegistro'));
    // [med_cuaderno_personal]
    Route::resource('med_cuaderno_personal', $controller.'\Medicina_trabajo\Med_cuaderno_personalController'); 

    // [hsi_actividad_economica_division]
    Route::resource('hsi_division', $controller.'\Medicina_trabajo\Hsi_actividad_economica_divisionController'); 
    // [hsi_actividad_economica_agrupacion]
    Route::resource('hsi_agrupacion', $controller.'\Medicina_trabajo\Hsi_actividad_economica_agrupacionController'); 
    // [hsi_tipo_registro]
    Route::resource('hsi_tipo_registro', $controller.'\Medicina_trabajo\Hsi_tipo_registroController'); 
    // [hsi_tipo]
    Route::resource('hsi_tipo', $controller.'\Medicina_trabajo\Hsi_tipoController'); 
    // [hsi_registro_datos]
    Route::resource('hsi_registro_datos', $controller.'\Medicina_trabajo\Hsi_registro_datosController'); 
    Route::post($urlAccion."/buscaPaciente_hsiCreate", array('uses' => $controller.'\Medicina_trabajo\Hsi_registro_datosController@buscaPaciente_hsi'));
    Route::post($urlAccion."/{id}/buscaPaciente_hsi", array('uses' => $controller.'\Medicina_trabajo\Hsi_registro_datosController@buscaPaciente_hsi'));

    Route::post($urlAccion."/buscaHsi_divisionCreate", array('uses' => $controller.'\Medicina_trabajo\Hsi_actividad_economica_divisionController@buscaHsi_division'));
    Route::post($urlAccion."/{id}/buscaHsi_division", array('uses' => $controller.'\Medicina_trabajo\Hsi_actividad_economica_divisionController@buscaHsi_division'));
    Route::post($urlAccion."/muestraDatosHsiCreate", array('uses' => $controller.'\Medicina_trabajo\Hsi_tipoController@muestraDatosHsi'));
    Route::post($urlAccion."/{id}/muestraDatosHsi", array('uses' => $controller.'\Medicina_trabajo\Hsi_tipoController@muestraDatosHsi'));  

    Route::post($urlAccion."/buscaPaciente_solicitudCreate", array('uses' => $controller.'\Medicina_trabajo\Med_registroController@buscaPaciente_solicitud'));
    Route::post($urlAccion."/{id}/buscaPaciente_solicitud", array('uses' => $controller.'\Medicina_trabajo\Med_registroController@buscaPaciente_solicitud'));
      
    // [med_programacion]
    // Route::resource('med_programacion', 'Medicina_trabajo\Med_programacionController'); 
    // // -------------------->> "Programados"
    // Route::post($urlAccion."/buscaPoblacion_med", ['uses' => 'Medicina_trabajo\Med_programacionController@buscaPoblacionMed']);
    // Route::post($urlAccion."/{id}/buscaPoblacion_med", ['uses' => 'Medicina_trabajo\Med_programacionController@buscaPoblacionMed']);
    // ------------------------------------ [ FIN MEDICINA DEL TRABAJO ] ------------------------------------

    // ---------------------------------------------------------------------------------
    // ------------------------------ Pestaña [ FARMACIA ] -----------------------------
    // ---------------------------------------------------------------------------------
    // [TIPOS DE TRANSACCIONES]
    route::resource('far_adm_tipotransaccion', $controller.'\Farmacia\Far_adm_tipotransaccionController');
    // [far_sucursales]
    route::resource('sucursal', $controller.'\Farmacia\Far_sucursalesController'); 
    // [far_adm_articulo]
    route::resource('articulo', $controller.'\Farmacia\Far_adm_articuloController'); 
    // ------------------------------------ [ FIN FARMACIA ] ------------------------------------
    
    // ---------------------------------------------------------------------------------
    // ------------------------------- Pestaña [ SALUD ] -------------------------------
    // ---------------------------------------------------------------------------------
    // [consulta_externa]
    
    route::resource('hcl_cabecera_registro', $controller.'\Salud\Hcl_cabecera_registroController');
    route::resource('hcl_lista_atencion', $controller.'\Salud\Hcl_lista_atencionController');

app/Models/Medicina_trabajo/Hsi_actividad_economica_agrupacion.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Hsi_actividad_economica_agrupacion extends Model
{ 
	protected $table = 'hsi_actividad_economica_agrupacion';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Hsi_actividad_economica_division.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Hsi_actividad_economica_division extends Model
{ 
	protected $table = 'hsi_actividad_economica_division';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Hsi_area.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Hsi_area extends Model
{ 
	protected $table = 'hsi_area';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Hsi_causa.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Hsi_causa extends Model
{ 
	protected $table = 'hsi_causa';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Hsi_registro_accidente_trabajo.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Hsi_registro_accidente_trabajo extends Model
{ 
	protected $table = 'hsi_registro_accidente_trabajo';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Hsi_registro_datos.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Hsi_registro_datos extends Model
{ 
	protected $table = 'hsi_registro_datos';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Hsi_tipo.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Hsi_tipo extends Model
{ 
	protected $table = 'hsi_tipo';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at 
}

app/Models/Medicina_trabajo/Hsi_tipo_registro.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Hsi_tipo_registro extends Model
{ 
	protected $table = 'hsi_tipo_registro';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
	const A = 1;
    const B = 2;
    const C = 3;
    const D = 4;
    const E = 5;
    const F = 6;
    const G = 7;
}

app/Models/Medicina_trabajo/Med_administracion.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Med_administracion extends Model
{ 
	protected $table = 'med_administracion';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Med_clasificacion.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Med_clasificacion extends Model
{ 
	protected $table = 'med_clasificacion';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Med_consolidado.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Med_consolidado extends Model
{ 
	protected $table = 'med_consolidado';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Med_cuaderno_personal.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Med_cuaderno_personal extends Model
{ 
	protected $table = 'med_cuaderno_personal';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Med_datos.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Med_datos extends Model
{ 
	protected $table = 'med_datos';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Med_estado.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Med_estado extends Model
{ 
	protected $table = 'med_estado';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at 
}

app/Models/Medicina_trabajo/Med_lista_cargos.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Med_lista_cargos extends Model
{ 
	protected $table = 'med_lista_cargos';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Med_programacion.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Med_programacion extends Model
{ 
	protected $table = 'med_programacion';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Med_registro.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Med_registro extends Model
{ 
	protected $table = 'med_registro';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at
}

app/Models/Medicina_trabajo/Med_tipo_cancelacion.php
<?php
namespace App\Models\Medicina_trabajo;

use Illuminate\Database\Eloquent\Model;

class Med_tipo_cancelacion extends Model
{ 
	protected $table = 'med_tipo_cancelacion';
	public $timestamps = false; //YA NO GUARDARÁ LOS CAMPOS created_at Y updated_at

	//---------------------------------------------
  	// CONSTANTES
  	const EFECTIVO = 1;
  	const DEPOSITO = 2;
  	const TRANSFERENCIA = 3;
}

resources/views/medicina_trabajo/med_administracion/create.blade.php
@extends('adminlte::page') 
@section('title', 'NUEVO REGISTRO')  
@section('content_header')
    <h1>NUEVO REGISTRO</h1>
@stop
 
@section('content')   
<form method="POST" action="{{ route('med_administracion.store') }}" autocomplete="off" id="form">
	{{ csrf_field() }}
	@include($model->rutaview.'form')
</form> 
@stop

resources/views/medicina_trabajo/med_administracion/edit.blade.php
@extends('adminlte::page') 
@section('title', 'EDITAR REGISTRO')  
@section('content_header')
    <h1>EDITAR REGISTRO</h1>
@stop
 
@section('content')  
<form method="POST" action="{{ route('med_administracion.update', $model->id) }}" autocomplete="off" id="form">
	{{ csrf_field() }}
		<input name="_method" type="hidden" value="PATCH"> 
	@include($model->rutaview.'form')
</form> 
@stop

resources/views/medicina_trabajo/med_administracion/form.blade.php
<div class="form-group">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <input type="hidden" id="txtAccion" value="{{ $model->accion }}">
    <input type="hidden" id="txtScenario" value="{{ $model->scenario }}">
    <input type="hidden" name="idalmacen" value="{{ $model->idalmacen }}">
      
  <div class="col-md-12">
    <div class="card ">
      <div class="card-header card-header-rose card-header-text">
        <div class="card-text">
          <h4 class="card-title">Datos</h4>
        </div>
      </div>
      <div class="card-body ">
        
        <div class="row">  
          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <label for="nombre" class="col-sm-6 col-form-label">Nombre</label>
            <div class="col-sm-12">
              <input type="text" class="form-control" id="nombre" name="nombre" value="{{ $model->nombre }}" placeholder="nombre">
            </div> 
          </div>     
          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6"> 
            <label for="descripcion" class="col-sm-6 col-form-label">Descripción</label>
            <div class="col-sm-12">
              <input type="text" class="form-control" id="descripcion" name="descripcion" value="{{ $model->descripcion }}" placeholder="">              
            </div>  
          </div>   
        </div>
      </div>
    </div>
  </div> 
</div> 

<a href="{{ URL::previous() }}" class="btn btn-primary">
  <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver
</a>
@if($model->scenario != 'view')
  <button type="submit" class="btn btn-success">
    <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> Guardar
  </button>
@endif

resources/views/medicina_trabajo/med_administracion/index.blade.php
@extends('adminlte::page')
@section('title', 'LISTA DE REGISTROS')
@section('content_header')
    <h1>LISTA DE REGISTROS</h1>
@stop   

@section('content')
<div class="card"> 
	<div class="card-header">
	 	<div class="row"> 
			<div class="col-xs-3 col-sm-3 col-md-2 col-lg-2" style="text-align: left;"> 
		        <a type="button" class="btn btn-block btn-outline-primary" href="{{ route('med_administracion.create') }}">
		            <span class="fa fa-plus" aria-hidden="true"></span> Nuevo registro
		        </a>
		    </div> 
		</div>
	</div> 
	<div class="card-body"> 
		<table id="empleador" class="table table-striped">
			<thead>
				<tr>
					<th>Nombre</th> 								
					<th>Descripción</th>
					<th>Usuario</th>					
					<th>Estado</th>
					<th></th>
				</tr> 
			</thead>
			<tbody>
				@foreach($model as $dato)					
					<tr role="row">
						<td class="text-left">{{ $dato->nombre }}</td>						
						<td class="text-left">{{ $dato->descripcion }}</td>						
						<td class="text-left">{{ $dato->usuario }}</td>	
						<td class="text-left"></td>						
						<td class="td-actions text-right"> 
							<a href="{{ route('med_administracion.edit', $dato->id) }}" class="btn btn-default btn-sm btn-round" rel="tooltip" title="Editar">
									<i class="fa fa-edit"></i>								
							</a>   					
						</td>
					</tr>					
				@endforeach
			</tbody>
		</table>
	</div>  
</div>
@stop

@section('js')
	<script>
		$(document).ready( function () {
		    $('#empleador').DataTable({
		    	"language":{
		    		"search": "Buscar",
		    		"lengthMenu": "Mostrar _MENU_ registros por página",
		    		"info": "Mostrando página _PAGE_ de _PAGES_",
		    		"paginate":{
			    		"previous": "Anterior",
			    		"next": "Siguiente",
			    		"first": "Primero",
			    		"last": "Ultimo"
			    	}
		    	}
		    });
		} );
	</script>	
@endsection 